site_name: Документация
docs_dir: src
theme:
  name: material
  favicon: 'assets/images/favicon.ico'
  logo: 'assets/images/logo.svg" alt="Exonum Logo'
  custom_dir: theme
  palette:
    primary: 'light green'
    accent: 'lime'

extra_css:
  - assets/stylesheets/extra.css
repo_name: 'exonum/exonum'
repo_url: 'https://github.com/exonum/exonum'
edit_uri: 'doc/blob/master/src'

site_url: 'http://35.196.80.152:9999/doc'
site_author: 'Exonum Team'
site_description: Exonum is a blockchain framework that allows to build secure permissioned blockchain applications.

copyright: © 2018 Exonum Team. Available under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" rel="license">CC BY-NC-SA 4.0</a> license

extra:
  og_image: 'assets/images/logo-docs.png'
  social:
    - type: 'github'
      link: 'https://github.com/exonum'
    - type: 'facebook'
      link: 'https://www.facebook.com/Exonum'
    - type: 'twitter'
      link: 'https://twitter.com/BitFuryGroup'
google_analytics:
  - 'UA-85962154-1'
  - 'auto'
markdown_extensions:
  - codehilite
  - admonition
  - meta
  - pymdownx.superfences
  - pymdownx.details
pages:
  # Short description of Exonum, documentation and how to use it
  - 'Что такое Exonum': 'index.md'
  - 'Общие сведения':
    # What is Exonum 'as a box', from point of view of external developer
    - 'Основные возможности': 'get-started/what-is-exonum.md'
    # How does Exonum look from the inside: nodes, validators, clients, blocks, consensus, genesis block;
    # links to necessary documentation parts
    - 'Обзор архитектуры': 'get-started/design-overview.md'
  - 'Архитектура':
    # Includes guidelines for services
    - 'Сервисы': 'architecture/services.md'
    # What is transaction? (purity, sequential consistency, non-replayability, signatures)
    - 'Транзакции': 'architecture/transactions.md'
    # How to make Public API communication (both server and client side)
    - 'Легкие клиенты': 'architecture/clients.md'
    # Consensus overview
    - 'Консенсус': 'architecture/consensus.md'
  - 'Сервисы':
    # Anchoring service documentation
    - 'Анкоринг': 'advanced/bitcoin-anchoring.md'
    # Time service
    - 'Оракул времени': 'advanced/time.md'
  - 'Глоссарий': 'glossary.md'
